repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: '.gitlab-ci.yml'
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.55.0'
    hooks:
    -   id: eslint
        entry: eslint --fix
        additional_dependencies:
        - eslint-plugin-cypress@2.15.1
        - eslint-plugin-chai-friendly@0.7.2
